"""Fix typo in shelter table

Revision ID: 90318c169a58
Revises: 
Create Date: 2024-09-28 13:57:39.124396

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90318c169a58'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_profile', schema=None) as batch_op:
        batch_op.drop_column('shelter_capacity_total')

    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=False))
        batch_op.drop_column('longtitude')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)

    with op.batch_alter_table('shelter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('longtitude', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('longitude')

    with op.batch_alter_table('provider_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shelter_capacity_total', mysql.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
